In [ ]:


from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  MOPS_380 = fn

Saving CI_SymbolPrice_2025-06-02T030407Z.csv to CI_SymbolPrice_2025-06-02T030407Z.csv
User uploaded file "CI_SymbolPrice_2025-06-02T030407Z.csv" with length 194689 bytes

In [ ]:

import pandas as pd
MOPS_380 = pd.read_csv(MOPS_380)

In [ ]:

print(MOPS_380.describe())
print(MOPS_380.info())
MOPS_380.shape

       Description FO 380 CST 3.5%S FOB Spore Cargo  \
count         6862                             3958
unique        6862                             3786
top     1998-01-02                           457.22
freq             1                                3

       FO 380 CST 3.5%S FOB Spore Cargo.1 FO 380 CST 3.5%S FOB Spore Cargo.2
count                                6862                               6862
unique                               5337                               5330
top                                 141.5                                163
freq                                   19                                 17
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6862 entries, 0 to 6861
Data columns (total 4 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Description                         6862 non-null   object
 1   FO 380 CST 3.5%S FOB Spore Cargo    3958 non-null   object
 2   FO 380 CST 3.5%S FOB Spore Cargo.1  6862 non-null   object
 3   FO 380 CST 3.5%S FOB Spore Cargo.2  6862 non-null   object
dtypes: object(4)
memory usage: 214.6+ KB
None

(6862, 4)

In [ ]:

uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  MOPS_180 = fn

MOPS_180 = pd.read_csv(MOPS_180)

print(MOPS_180.describe())
print(MOPS_180.info())
MOPS_180.shape

Saving CI_SymbolPrice_2025-06-02T030821Z.csv to CI_SymbolPrice_2025-06-02T030821Z.csv
User uploaded file "CI_SymbolPrice_2025-06-02T030821Z.csv" with length 287211 bytes
       Description FO 180 CST 3.5%S FOB Spore Cargo  \
count        11506                             3958
unique       11506                             3770
top     1980-01-02                           389.69
freq             1                                3

       FO 180 CST 3.5%S FOB Spore Cargo.1 FO 180 CST 3.5%S FOB Spore Cargo.2
count                               11506                              11506
unique                               5447                               5437
top                                   172                                169
freq                                  116                                110
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11506 entries, 0 to 11505
Data columns (total 4 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Description                         11506 non-null  object
 1   FO 180 CST 3.5%S FOB Spore Cargo    3958 non-null   object
 2   FO 180 CST 3.5%S FOB Spore Cargo.1  11506 non-null  object
 3   FO 180 CST 3.5%S FOB Spore Cargo.2  11506 non-null  object
dtypes: object(4)
memory usage: 359.7+ KB
None

(11506, 4)

In [ ]:
# prompt: let's upload another dataset, this one will be named main

uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  main = fn

main = pd.read_csv(main)

print(main.describe())
print(main.info())
main.shape

Saving heards_structured_cleaned_09_Trades.csv to heards_structured_cleaned_09_Trades.csv
User uploaded file "heards_structured_cleaned_09_Trades.csv" with length 35173566 bytes
               price          grade     volume_min     volume_max  \
count  167429.000000  154348.000000  119342.000000  119342.000000
mean       75.572555     327.493975      22.966684      22.303581
std       138.735891      88.002117       7.035724       7.937481
min      -100.000000     180.000000      20.000000       2.000000
25%         1.000000     180.000000      20.000000      20.000000
50%         5.000000     380.000000      20.000000      20.000000
75%        25.000000     380.000000      20.000000      20.000000
max       673.000000     380.000000      40.000000      40.000000

       duration_days    start_month      end_month
count  167429.000000  167429.000000  167429.000000
mean       28.057577       6.375520       7.172999
std        81.426990       3.387527       3.317624
min         0.000000       1.000000       1.000000
25%         4.000000       4.000000       5.000000
50%         4.000000       7.000000       7.000000
75%         5.000000       9.000000      10.000000
max       365.000000      12.000000      12.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167429 entries, 0 to 167428
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   updatedDate    167429 non-null  object
 1   start_date     167429 non-null  object
 2   end_date       167429 non-null  object
 3   action_type    167429 non-null  object
 4   party          154348 non-null  object
 5   price          167429 non-null  float64
 6   price_basis    154228 non-null  object
 7   grade          154348 non-null  float64
 8   incoterm       148688 non-null  object
 9   location       147922 non-null  object
 10  volume_min     119342 non-null  float64
 11  volume_max     119342 non-null  float64
 12  headline       167429 non-null  object
 13  duration_days  167429 non-null  int64
 14  start_month    167429 non-null  int64
 15  end_month      167429 non-null  int64
dtypes: float64(4), int64(3), object(9)
memory usage: 20.4+ MB
None

<ipython-input-7-cacb62726f7a>:9: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  main = pd.read_csv(main)

(167429, 16)

In [ ]:
print(main['price_basis'].dropna().unique())

['MOPS 380' 'MOPS 180']

In [ ]:
pd.set_option('display.max_colwidth', None)
print(main[main['price_basis'].notnull()][['headline', 'price_basis', 'price']].sample(5))

                                                                                                                        headline  \
123397  Asia 148: Platts HSFO 180cst FOB Straits 15-30, VITOLSG raises bid Aug 4-Aug 8 100% MOPS 180 5 Day $1.50  for 20-20 "inc
67845   Platts HSFO 380cst FOB Straits 15-30, GUNVORSG raises bid Nov 4-Nov 8 100% MOPS 380 5 Day $-1.00  for 40-40 OCO  8:17:31
125267  Asia 422: Platts HSFO 180cst FOB Straits 15-30, MERCURIASG raises bid Jul 23-Jul 27 100% MOPS 180 5 Day $1.00  for 40-40
81305   Asia 286: Platts HSFO 380cst FOB Straits 15-30, SIETCO offers Dec 25-Dec 29 100% MOPS 380 5 Day $9.00  for 20-20 7:57:20
25146      Platts HSFO 180cst FOB Straits 15-30, BPSG withdraws offer Jul 25-Jul 29 100% MOPS 180 5 Day $4.00  for 20-20 "BP GTC

       price_basis  price
123397    MOPS 180    1.5
67845     MOPS 380   -1.0
125267    MOPS 180    1.0
81305     MOPS 380    9.0
25146     MOPS 180    4.0

In [ ]:
# Step 1: Check a few rows before conversion
print(main[['start_date']].head())

# Step 2: Calculate % filled before conversion
filled_before = main['start_date'].notnull().mean() * 100
print(f"Start date filled before conversion: {filled_before:.2f}%")

# Step 3: Convert to datetime
main['start_date'] = pd.to_datetime(main['start_date'], errors='coerce')

# Step 4: Check a few rows after conversion
print(main[['start_date']].head())

# Step 5: Calculate % filled after conversion
filled_after = main['start_date'].notnull().mean() * 100
print(f"Start date filled after conversion: {filled_after:.2f}%")

   start_date
0  2025-06-17
1  2025-06-17
2  2025-06-17
3  2025-06-17
4  2025-06-17
Start date filled before conversion: 100.00%
  start_date
0 2025-06-17
1 2025-06-17
2 2025-06-17
3 2025-06-17
4 2025-06-17
Start date filled after conversion: 100.00%

In [ ]:
# Descriptive stats for MOPS 380 prices
price_stats_380 = main[main['price_basis'] == 'MOPS 380']['price'].describe()
num_filled = main[main['price_basis'] == 'MOPS 380']['price'].notnull().sum()
print(price_stats_380)
print(f"\n# of non-null prices for MOPS 380: {num_filled}")

count    116320.000000
mean         64.378105
std         134.081718
min         -31.000000
25%           1.250000
50%           5.000000
75%          17.000000
max         673.000000
Name: price, dtype: float64

# of non-null prices for MOPS 380: 116320

In [ ]:
# Step 1: Clean MOPS 380
mops_380_cleaned = MOPS_380[['Description', 'FO 380 CST 3.5%S FOB Spore Cargo']].copy()
mops_380_cleaned.columns = ['mops_date', 'mops_price']

# Use explicit date format to avoid warning
mops_380_cleaned['mops_date'] = pd.to_datetime(
    mops_380_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce'
)

# Convert price to numeric
mops_380_cleaned['mops_price'] = pd.to_numeric(mops_380_cleaned['mops_price'], errors='coerce')

# Drop nulls and sort
mops_380_cleaned = mops_380_cleaned.dropna().sort_values('mops_date')

# Step 2: Filter for MOPS 380 rows in main
main_380 = main[main['price_basis'] == 'MOPS 380'].copy()
main_380 = main_380.sort_values('start_date')

# Step 3: Match nearest MOPS date ≤ start_date
main_380 = pd.merge_asof(main_380, mops_380_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

# Step 4: Compute true price
main_380['price'] = main_380['price'] + main_380['mops_price']

# Step 5: Update original main DataFrame
main.loc[main['price_basis'] == 'MOPS 380', 'price'] = main_380['price'].values

# Step 6: Print descriptive stats
price_stats_380 = main[main['price_basis'] == 'MOPS 380']['price'].describe()
num_filled_380 = main[main['price_basis'] == 'MOPS 380']['price'].notnull().sum()
print(price_stats_380)
print(f"\n# of non-null prices for MOPS 380: {num_filled_380}")

count    116320.000000
mean        845.416487
std         199.347750
min         302.550000
25%         751.057500
50%         828.350000
75%         931.570000
max        1786.650000
Name: price, dtype: float64

# of non-null prices for MOPS 380: 116320

In [ ]:
print(main[main['price_basis'] != 'MOPS 380']['price'].describe())

count    51109.000000
mean       101.050229
std        145.614369
min       -100.000000
25%          1.000000
50%          6.000000
75%        285.953347
max        670.000000
Name: price, dtype: float64

In [ ]:
# Step 1: Clean MOPS 180
mops_180_cleaned = MOPS_180[['Description', 'FO 180 CST 3.5%S FOB Spore Cargo']].copy()
mops_180_cleaned.columns = ['mops_date', 'mops_price']

# Use explicit date format
mops_180_cleaned['mops_date'] = pd.to_datetime(
    mops_180_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce'
)

# Convert price to numeric
mops_180_cleaned['mops_price'] = pd.to_numeric(mops_180_cleaned['mops_price'], errors='coerce')

# Drop nulls and sort
mops_180_cleaned = mops_180_cleaned.dropna().sort_values('mops_date')

# Step 2: Filter for MOPS 180 rows in main
main_180 = main[main['price_basis'] == 'MOPS 180'].copy()
main_180 = main_180.sort_values('start_date')

# Step 3: Match nearest MOPS date ≤ start_date
main_180 = pd.merge_asof(main_180, mops_180_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

# Step 4: Compute true price
main_180['price'] = main_180['price'] + main_180['mops_price']

# Step 5: Update original main DataFrame
main.loc[main['price_basis'] == 'MOPS 180', 'price'] = main_180['price'].values

# Step 6: Print descriptive stats
price_stats_180 = main[main['price_basis'] == 'MOPS 180']['price'].describe()
num_filled_180 = main[main['price_basis'] == 'MOPS 180']['price'].notnull().sum()
print(price_stats_180)
print(f"\n# of non-null prices for MOPS 180: {num_filled_180}")

count    37908.000000
mean       457.171267
std        156.364514
min        103.890000
25%        364.550000
50%        435.800000
75%        506.472500
max       1342.740000
Name: price, dtype: float64

# of non-null prices for MOPS 180: 37908

In [ ]:
# Step 1: % filled per column
filled_percent = (main.notnull().mean() * 100).round(2)
print("📊 % of Filled Values per Column:\n")
print(filled_percent)

print("\n" + "="*60 + "\n")

# Step 2: Price stats overall
print("📈 Price Stats – ALL rows:")
print(main['price'].describe())
print(f"Total rows: {len(main)}\nNon-null price rows: {main['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Step 3: Price stats where price_basis is null
print("📉 Price Stats – price_basis is NULL:")
null_mask = main['price_basis'].isnull()
print(main[null_mask]['price'].describe())
print(f"# of rows: {null_mask.sum()}\nNon-null price rows: {main[null_mask]['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Step 4: Price stats where price_basis == MOPS 180
print("💡 Price Stats – MOPS 180:")
m180_mask = main['price_basis'] == 'MOPS 180'
print(main[m180_mask]['price'].describe())
print(f"# of rows: {m180_mask.sum()}\nNon-null price rows: {main[m180_mask]['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Step 5: Price stats where price_basis == MOPS 380
print("💡 Price Stats – MOPS 380:")
m380_mask = main['price_basis'] == 'MOPS 380'
print(main[m380_mask]['price'].describe())
print(f"# of rows: {m380_mask.sum()}\nNon-null price rows: {main[m380_mask]['price'].notnull().sum()}")

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             92.19
price            100.00
price_basis       92.12
grade             92.19
incoterm          88.81
location          88.35
volume_min        71.28
volume_max        71.28
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
dtype: float64

============================================================

📈 Price Stats – ALL rows:
count    167429.000000
mean        712.094205
std         275.879738
min           6.675100
25%         471.820000
50%         774.760000
75%         876.530000
max        1786.650000
Name: price, dtype: float64
Total rows: 167429
Non-null price rows: 167429

============================================================

📉 Price Stats – price_basis is NULL:
count    13201.000000
mean       269.367959
std         75.413903
min          6.675100
25%        246.706839
50%        306.531794
75%        312.632611
max        546.628892
Name: price, dtype: float64
# of rows: 13201
Non-null price rows: 13201

============================================================

💡 Price Stats – MOPS 180:
count    37908.000000
mean       457.171267
std        156.364514
min        103.890000
25%        364.550000
50%        435.800000
75%        506.472500
max       1342.740000
Name: price, dtype: float64
# of rows: 37908
Non-null price rows: 37908

============================================================

💡 Price Stats – MOPS 380:
count    116320.000000
mean        845.416487
std         199.347750
min         302.550000
25%         751.057500
50%         828.350000
75%         931.570000
max        1786.650000
Name: price, dtype: float64
# of rows: 116320
Non-null price rows: 116320

In [ ]:
pd.set_option('display.max_colwidth', None)
print(main[main['price_basis'] == 'MOPS 380'][['headline', 'price', 'start_date']].sample(5))

                                                                                                                        headline  \
103588  Asia 252: Platts HSFO 380cst FOB Straits 15-30, VITOLSG bids Apr 24-Apr 28 100% MOPS 380 5 Day $-3.00  for 20-20 "inco"
26426   Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Jun 12-Jun 16 100% MOPS 380 5 Day $0.00  for 20-20 OCO  8:14:20.4
1570    Platts HSFO 380cst FOB Straits 15-30, VITOLSG raises bid May 9-May 13 100% MOPS 380 5 Day $2.00  for 20-20 "inco" OCO  8
125066     Asia 228: Platts HSFO 380cst FOB Straits 15-30, VITOLSG bids Jul 19-Jul 23 100% MOPS 380 5 Day $2.00  for 20-20 "inco
16340   Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Apr 15-Apr 19 100% MOPS 380 5 Day $-3.00  for 40-40 OCO  8:28:42.

          price start_date
103588  1052.73 2019-04-28
26426   1008.45 2023-06-12
1570     772.09 2025-05-06
125066  1361.67 2018-07-19
16340    887.31 2024-04-15

In [ ]:
# Use the correct column: .1 instead of base
mops_380_cleaned = MOPS_380[['Description', 'FO 380 CST 3.5%S FOB Spore Cargo.1']].copy()
mops_380_cleaned.columns = ['mops_date', 'mops_price']

# Convert types
mops_380_cleaned['mops_date'] = pd.to_datetime(mops_380_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce')
mops_380_cleaned['mops_price'] = pd.to_numeric(mops_380_cleaned['mops_price'], errors='coerce')
mops_380_cleaned = mops_380_cleaned.dropna().sort_values('mops_date')

# Redo merge
main_380 = main[main['price_basis'] == 'MOPS 380'].copy()
main_380 = main_380.sort_values('start_date')

main_380 = pd.merge_asof(main_380, mops_380_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

main_380['price'] = main_380['price'] + main_380['mops_price']

# Overwrite
main.loc[main['price_basis'] == 'MOPS 380', 'price'] = main_380['price'].values

In [ ]:
# Updated price stats for MOPS 380 after correction
price_stats_380 = main[main['price_basis'] == 'MOPS 380']['price'].describe()
num_filled_380 = main[main['price_basis'] == 'MOPS 380']['price'].notnull().sum()

print("💡 Updated Price Stats – MOPS 380:")
print(price_stats_380)
print(f"# of rows: {num_filled_380}")

💡 Updated Price Stats – MOPS 380:
count    116320.000000
mean       1235.955678
std         254.975483
min         418.070000
25%        1123.287500
50%        1246.355000
75%        1380.370000
max        2418.180000
Name: price, dtype: float64
# of rows: 116320

In [ ]:
# Use .2 column (likely true MOPS 380 benchmark prices)
mops_380_cleaned = MOPS_380[['Description', 'FO 380 CST 3.5%S FOB Spore Cargo.2']].copy()
mops_380_cleaned.columns = ['mops_date', 'mops_price']

# Parse
mops_380_cleaned['mops_date'] = pd.to_datetime(mops_380_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce')
mops_380_cleaned['mops_price'] = pd.to_numeric(mops_380_cleaned['mops_price'], errors='coerce')
mops_380_cleaned = mops_380_cleaned.dropna().sort_values('mops_date')

# Restore old price values if needed
# main['price'] = main['price_old']  # Uncomment if rollback needed

# Recalculate
main_380 = main[main['price_basis'] == 'MOPS 380'].copy()
main_380 = main_380.sort_values('start_date')

main_380 = pd.merge_asof(main_380, mops_380_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

main_380['price'] = main_380['price'] + main_380['mops_price']

# Overwrite
main.loc[main['price_basis'] == 'MOPS 380', 'price'] = main_380['price'].values

In [ ]:
price_stats_380 = main[main['price_basis'] == 'MOPS 380']['price'].describe()
print(price_stats_380)

count    116320.000000
mean       1626.454869
std         314.078154
min         642.580000
25%        1498.837146
50%        1643.535000
75%        1813.412500
max        2859.090000
Name: price, dtype: float64

In [ ]:
main = pd.read_csv("heards_structured_cleaned_09_Trades.csv")
main['start_date'] = pd.to_datetime(main['start_date'], errors='coerce')

<ipython-input-24-e63c25a0aba0>:1: DtypeWarning: Columns (4,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  main = pd.read_csv("heards_structured_cleaned_09_Trades.csv")

In [ ]:
main['price_raw'] = main['price']

In [ ]:
main['start_date'] = pd.to_datetime(main['start_date'], errors='coerce')

In [ ]:
# % of filled rows per column
filled_percent = (main.notnull().mean() * 100).round(2)
print("📊 % of Filled Values per Column:\n")
print(filled_percent)

print("\n" + "="*60 + "\n")

# Stats: All prices
print("📈 Price Stats – ALL rows:")
print(main['price'].describe())
print(f"Total rows: {len(main)}\nNon-null price rows: {main['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Stats: Price basis is NULL
print("📉 Price Stats – price_basis is NULL:")
null_mask = main['price_basis'].isnull()
print(main[null_mask]['price'].describe())
print(f"# of rows: {null_mask.sum()}\nNon-null price rows: {main[null_mask]['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Stats: MOPS 180
print("💡 Price Stats – MOPS 180:")
m180_mask = main['price_basis'] == 'MOPS 180'
print(main[m180_mask]['price'].describe())
print(f"# of rows: {m180_mask.sum()}\nNon-null price rows: {main[m180_mask]['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

# Stats: MOPS 380
print("💡 Price Stats – MOPS 380:")
m380_mask = main['price_basis'] == 'MOPS 380'
print(main[m380_mask]['price'].describe())
print(f"# of rows: {m380_mask.sum()}\nNon-null price rows: {main[m380_mask]['price'].notnull().sum()}")

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             92.19
price            100.00
price_basis       92.12
grade             92.19
incoterm          88.81
location          88.35
volume_min        71.28
volume_max        71.28
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

============================================================

📈 Price Stats – ALL rows:
count    167429.000000
mean         75.572555
std         138.735891
min        -100.000000
25%           1.000000
50%           5.000000
75%          25.000000
max         673.000000
Name: price, dtype: float64
Total rows: 167429
Non-null price rows: 167429

============================================================

📉 Price Stats – price_basis is NULL:
count    13201.000000
mean       269.367959
std         75.413903
min          6.675100
25%        246.706839
50%        306.531794
75%        312.632611
max        546.628892
Name: price, dtype: float64
# of rows: 13201
Non-null price rows: 13201

============================================================

💡 Price Stats – MOPS 180:
count    37908.000000
mean        42.435626
std        115.348585
min       -100.000000
25%          0.000000
50%          3.000000
75%          9.000000
max        670.000000
Name: price, dtype: float64
# of rows: 37908
Non-null price rows: 37908

============================================================

💡 Price Stats – MOPS 380:
count    116320.000000
mean         64.378105
std         134.081718
min         -31.000000
25%           1.250000
50%           5.000000
75%          17.000000
max         673.000000
Name: price, dtype: float64
# of rows: 116320
Non-null price rows: 116320

In [ ]:
# Use .2 column (validated) from MOPS 380
mops_380_cleaned = MOPS_380[['Description', 'FO 380 CST 3.5%S FOB Spore Cargo.2']].copy()
mops_380_cleaned.columns = ['mops_date', 'mops_price']
mops_380_cleaned['mops_date'] = pd.to_datetime(mops_380_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce')
mops_380_cleaned['mops_price'] = pd.to_numeric(mops_380_cleaned['mops_price'], errors='coerce')
mops_380_cleaned = mops_380_cleaned.dropna().sort_values('mops_date')

main_380 = main[main['price_basis'] == 'MOPS 380'].copy().sort_values('start_date')
main_380 = pd.merge_asof(main_380, mops_380_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

main_380['price'] = main_380['price_raw'] + main_380['mops_price']
main.loc[main['price_basis'] == 'MOPS 380', 'price'] = main_380['price'].values

In [ ]:
# Use .2 column (validated) from MOPS 180
mops_180_cleaned = MOPS_180[['Description', 'FO 180 CST 3.5%S FOB Spore Cargo.2']].copy()
mops_180_cleaned.columns = ['mops_date', 'mops_price']
mops_180_cleaned['mops_date'] = pd.to_datetime(mops_180_cleaned['mops_date'], format='%Y-%m-%d', errors='coerce')
mops_180_cleaned['mops_price'] = pd.to_numeric(mops_180_cleaned['mops_price'], errors='coerce')
mops_180_cleaned = mops_180_cleaned.dropna().sort_values('mops_date')

main_180 = main[main['price_basis'] == 'MOPS 180'].copy().sort_values('start_date')
main_180 = pd.merge_asof(main_180, mops_180_cleaned,
                         left_on='start_date', right_on='mops_date',
                         direction='backward')

main_180['price'] = main_180['price_raw'] + main_180['mops_price']
main.loc[main['price_basis'] == 'MOPS 180', 'price'] = main_180['price'].values

In [ ]:
# Final stats after price correction
print("📈 Final Price Stats – ALL rows:")
print(main['price'].describe())
print(f"Total rows: {len(main)}\nNon-null price rows: {main['price'].notnull().sum()}")

print("\n" + "="*60 + "\n")

print("📉 Price Stats – price_basis is NULL:")
null_mask = main['price_basis'].isnull()
print(main[null_mask]['price'].describe())
print(f"# of rows: {null_mask.sum()}")

print("\n" + "="*60 + "\n")

print("💡 Price Stats – MOPS 180:")
m180_mask = main['price_basis'] == 'MOPS 180'
print(main[m180_mask]['price'].describe())
print(f"# of rows: {m180_mask.sum()}")

print("\n" + "="*60 + "\n")

print("💡 Price Stats – MOPS 380:")
m380_mask = main['price_basis'] == 'MOPS 380'
print(main[m380_mask]['price'].describe())
print(f"# of rows: {m380_mask.sum()}")

📈 Final Price Stats – ALL rows:
count    167429.000000
mean        440.765601
std         159.297409
min           6.675100
25%         338.460000
50%         424.270000
75%         490.460000
max        1342.720000
Name: price, dtype: float64
Total rows: 167429
Non-null price rows: 167429

============================================================

📉 Price Stats – price_basis is NULL:
count    13201.000000
mean       269.367959
std         75.413903
min          6.675100
25%        246.706839
50%        306.531794
75%        312.632611
max        546.628892
Name: price, dtype: float64
# of rows: 13201

============================================================

💡 Price Stats – MOPS 180:
count    37908.000000
mean       457.151267
std        156.364514
min        103.870000
25%        364.530000
50%        435.780000
75%        506.452500
max       1342.720000
Name: price, dtype: float64
# of rows: 37908

============================================================

💡 Price Stats – MOPS 380:
count    116320.000000
mean        454.877296
std         155.857071
min          85.590000
25%         364.235000
50%         431.620000
75%         497.672500
max        1341.700000
Name: price, dtype: float64
# of rows: 116320

In [ ]:
print(f"# of rows with null price_basis: {main['price_basis'].isnull().sum()}")

# of rows with null price_basis: 13201

In [ ]:
pd.set_option('display.max_colwidth', None)
print(main[main['price_basis'].isnull()][['headline', 'price']].sample(10))

                                                                                                                        headline  \
155762  platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe
167026  asia 1810: platts hsfo 380cst fob straits 15-30, hl taking gunvorsg <p>   offer aug 25, 2017-aug 29, 2017  100% mops 380
162429                                                  asia 1714: platts hsfo fob fuj: physical bids finals on close (380 cst)
159631                                                                     platts hsfo: physical bids finals on close (180 cst):
157510                                                                  platts hsfo: physical offers finals on close (380 cst):
154820                                                                  platts hsfo: physical offers finals on close (380 cst):
165692                                                                    asia 390: platts hsfo: physical bids summary (380 cst)
160083                                                                     platts hsfo: physical bids finals on close (380 cst):
161300  asia 2221: platts hsfo 180cst fob straits 15-30, vitolsg buys from gunvorsg oct 26, 2019-oct 30, 2019  100% mops 180 5 d
160002                                                                     platts hsfo: physical bids finals on close (180 cst):

             price
155762  113.601108
167026  203.696314
162429  306.531794
159631  303.826789
157510  312.632611
154820  312.632611
165692  322.916202
160083  307.196330
161300  169.280237
160002  303.826789

In [ ]:
# Create a mask for rows where price_basis is null
mask_null_basis = main['price_basis'].isna()

# Extract lowercase headline for easier matching
headlines = main.loc[mask_null_basis, 'headline'].str.lower()

# Define conditions based on regex patterns
is_180 = headlines.str.contains(r'\b180\b|\b180cst\b')
is_380 = headlines.str.contains(r'\b380\b|\b380cst\b')

# Update the null values accordingly
main.loc[mask_null_basis & is_180, 'price_basis'] = 'MOPS 180'
main.loc[mask_null_basis & is_380, 'price_basis'] = 'MOPS 380'

# Print final check
print("✅ Remaining null price_basis values:", main['price_basis'].isna().sum())

✅ Remaining null price_basis values: 2670

In [ ]:
# Filter remaining null price_basis rows
remaining_null_basis = main[main['price_basis'].isna()][['headline', 'price']]

# Show 10 random examples
print(remaining_null_basis.sample(10, random_state=42))

                                                                                                                        headline  \
161058  asia 260: platts hsfo: for cargoes loading in the middle east, platts will only publish offers wherein sellers specify a
155508  platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe
163868                                     asia 79: platts hsfo: as of july 1, 2015, platts no longer publishes fob singapore or
161008                                             asia 533: platts asia deals summary: refined oil products: december 17, 2019:
163984  asia 160: platts hsfo: for cargoes loading in the middle east, platts will only publish offers wherein sellers specify a
163573                                             asia 1610: platts asia deals summary: refined oil products: october 10, 2018:
166011                                    asia 186: platts hsfo: as of july 1, 2015, platts no longer publishes fob singapore or
162020  asia 260: platts hsfo: for cargoes loading in the middle east, platts will only publish offers wherein sellers specify a
156004  platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe
164034                                    asia 262: platts hsfo: as of july 1, 2015, platts no longer publishes fob singapore or

             price
161058  167.672022
155508  113.601108
163868  101.315500
161008  237.526201
163984  142.842221
163573  240.774513
166011  149.505259
162020  167.672022
156004  113.601108
164034  143.890044

In [ ]:
# Step 1: Extract remaining rows with null price_basis
remaining_null = main[main['price_basis'].isna()].copy()

# Step 2: Merge with MOPS 180 and MOPS 380 datasets using closest available date
remaining_null_sorted = remaining_null.sort_values("start_date")

# Merge with MOPS 180
merged_180 = pd.merge_asof(
    remaining_null_sorted,
    mops_180_cleaned.rename(columns={"mops_date": "date", "mops_price": "price_180"}).sort_values("date"),
    left_on="start_date",
    right_on="date",
    direction="backward"
)

# Merge with MOPS 380
merged_180_380 = pd.merge_asof(
    merged_180,
    mops_380_cleaned.rename(columns={"mops_date": "date", "mops_price": "price_380"}).sort_values("date"),
    left_on="start_date",
    right_on="date",
    direction="backward"
)

# Step 3: Compare with actual price and assign closest price_basis
def infer_basis(row):
    diff_180 = abs(row['price'] - row['price_180']) if pd.notnull(row['price_180']) else float('inf')
    diff_380 = abs(row['price'] - row['price_380']) if pd.notnull(row['price_380']) else float('inf')
    return "MOPS 180" if diff_180 < diff_380 else "MOPS 380"

merged_180_380['inferred_basis'] = merged_180_380.apply(infer_basis, axis=1)

# Step 4: Update the main dataframe
main.loc[merged_180_380.index, 'price_basis'] = merged_180_380['inferred_basis'].values

In [ ]:
import pandas as pd

# === 1. % of filled values per column ===
print("📊 % of Filled Values per Column:\n")
fill_rates = main.notnull().mean() * 100
print(fill_rates.round(2))

# === 2. Total number of rows ===
print("\n📄 Total Rows:", len(main))

# === 3. Price Stats – ALL rows ===
print("\n📈 Price Stats – ALL rows:")
print(main['price'].describe())
print("Total rows:", len(main))
print("Non-null price rows:", main['price'].notnull().sum())

# === 4. Price Stats – MOPS 180 ===
print("\n💡 Price Stats – MOPS 180:")
mops_180 = main[main['price_basis'] == 'MOPS 180']
print(mops_180['price'].describe())
print("# of rows:", len(mops_180))

# === 5. Price Stats – MOPS 380 ===
print("\n💡 Price Stats – MOPS 380:")
mops_380 = main[main['price_basis'] == 'MOPS 380']
print(mops_380['price'].describe())
print("# of rows:", len(mops_380))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             92.19
price            100.00
price_basis       98.41
grade             92.19
incoterm          88.81
location          88.35
volume_min        71.28
volume_max        71.28
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

📄 Total Rows: 167429

📈 Price Stats – ALL rows:
count    167429.000000
mean        440.765601
std         159.297409
min           6.675100
25%         338.460000
50%         424.270000
75%         490.460000
max        1342.720000
Name: price, dtype: float64
Total rows: 167429
Non-null price rows: 167429

💡 Price Stats – MOPS 180:
count    41569.000000
mean       442.474913
std        155.995488
min        100.256343
25%        331.090000
50%        421.540000
75%        496.260000
max       1342.720000
Name: price, dtype: float64
# of rows: 41569

💡 Price Stats – MOPS 380:
count    123190.000000
mean        446.140811
std         156.614664
min           6.675100
25%         350.552500
50%         426.730000
75%         491.280000
max        1341.700000
Name: price, dtype: float64
# of rows: 123190

In [ ]:
# Filter rows where price_basis is still null
remaining_null_basis = main[main['price_basis'].isnull()]

# Display headline and price for first 10 such rows
remaining_null_basis[['headline', 'price']].head(10)

,headline,price
154412,bangladesh's bpc buys up to 1.275 mil mt of oil products for h2 2025 delivery,125.107976
154525,dirty tankers: evgenia i 270kt cr apr10 pg-skorea w59.5 hanwha,209.641062
154553,"~~platts fuel oil: cargo moc: deal summary: platts hsfo med crg cif bss barcelona 10-25, trafi sells to gltd apr 10, 202",125.028523
154617,amend: platts hsfo trade summary: 7 trades,182.597772
154626,~~platts fuel oil: cargo moc: deal summary:,169.894654
154673,"platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe",113.601108
154682,"platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe",113.601108
154687,"platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe",113.601108
154693,"platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe",113.601108
154698,"platts hsfo/mf0.5% physical: for cargoes loading in the middle east, platts will only publish offers wherein sellers spe",113.601108

In [ ]:
total_rows_before = len(main)
print("Total rows before drop:", total_rows_before)

Total rows before drop: 167429

In [ ]:
main_filtered = main[main['price_basis'].isin(['MOPS 180', 'MOPS 380'])]

In [ ]:
remaining_rows = len(main_filtered)
print("Remaining rows after dropping null or unknown price_basis:", remaining_rows)

Remaining rows after dropping null or unknown price_basis: 164759

In [ ]:
main = main_filtered

In [ ]:
# Replace with your actual DataFrame name if it's different
df = main_filtered  # or use `main` if you've overwritten it

# Print % of filled values per column
filled_percent = df.notnull().mean() * 100
print("📊 % of Filled Values per Column:\n")
print(filled_percent.round(2))

# Print total number of rows
print("\n📄 Total Rows:", len(df))

# Print data types
print("\n📂 Data Types:")
print(df.dtypes)

# Print basic price stats overall
print("\n📈 Price Stats – ALL rows:")
print(df["price"].describe())

# Print price stats by basis
for basis in ["MOPS 180", "MOPS 380"]:
    subset = df[df["price_basis"] == basis]
    print(f"\n💡 Price Stats – {basis}:")
    print(subset["price"].describe())
    print(f"# of rows: {len(subset)}")

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             93.68
price            100.00
price_basis      100.00
grade             93.68
incoterm          90.25
location          89.78
volume_min        72.43
volume_max        72.43
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

📄 Total Rows: 164759

📂 Data Types:
updatedDate              object
start_date       datetime64[ns]
end_date                 object
action_type              object
party                    object
price                   float64
price_basis              object
grade                   float64
incoterm                 object
location                 object
volume_min              float64
volume_max              float64
headline                 object
duration_days             int64
start_month               int64
end_month                 int64
price_raw               float64
dtype: object

📈 Price Stats – ALL rows:
count    164759.000000
mean        445.215898
std         156.466305
min           6.675100
25%         344.625000
50%         425.950000
75%         492.280000
max        1342.720000
Name: price, dtype: float64

💡 Price Stats – MOPS 180:
count    41569.000000
mean       442.474913
std        155.995488
min        100.256343
25%        331.090000
50%        421.540000
75%        496.260000
max       1342.720000
Name: price, dtype: float64
# of rows: 41569

💡 Price Stats – MOPS 380:
count    123190.000000
mean        446.140811
std         156.614664
min           6.675100
25%         350.552500
50%         426.730000
75%         491.280000
max        1341.700000
Name: price, dtype: float64
# of rows: 123190

In [ ]:
# Display all unique values in the 'grade' column, including NaNs
unique_grades = main['grade'].dropna().unique()
unique_grades_sorted = sorted(unique_grades)

print(f"Total unique non-null grades: {len(unique_grades_sorted)}")
print("Unique grades (non-null):", unique_grades_sorted)

# Count NaNs separately
num_null_grades = main['grade'].isna().sum()
print(f"Number of null grade values: {num_null_grades}")

Total unique non-null grades: 2
Unique grades (non-null): [np.float64(180.0), np.float64(380.0)]
Number of null grade values: 10411

In [ ]:
main.drop(columns=['grade'], inplace=True)

In [ ]:
df = main

# Print % of filled values per column
filled_percent = df.notnull().mean() * 100
print("📊 % of Filled Values per Column:\n")
print(filled_percent.round(2))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             93.68
price            100.00
price_basis      100.00
incoterm          90.25
location          89.78
volume_min        72.43
volume_max        72.43
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

In [ ]:
# Count unique non-null values and show the most common ones
print("🔍 Total unique non-null incoterms:", main['incoterm'].nunique())
print("📦 Top 10 most frequent incoterms:\n", main['incoterm'].value_counts(dropna=True).head(10))

# Check number of missing values
missing_incoterm = main['incoterm'].isna().sum()
print(f"\n❓ Missing incoterm values: {missing_incoterm}")

🔍 Total unique non-null incoterms: 1
📦 Top 10 most frequent incoterms:
 incoterm
FOB    148688
Name: count, dtype: int64

❓ Missing incoterm values: 16071

In [ ]:
main = main.drop(columns=["incoterm"])

In [ ]:
df = main

# Print % of filled values per column
filled_percent = df.notnull().mean() * 100
print("📊 % of Filled Values per Column:\n")
print(filled_percent.round(2))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             93.68
price            100.00
price_basis      100.00
location          89.78
volume_min        72.43
volume_max        72.43
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

In [ ]:
# Total unique non-null values in 'party'
unique_parties = main['party'].dropna().unique()
print(f"🔍 Total unique non-null parties: {len(unique_parties)}")

# Top 10 most frequent values
print("📦 Top 10 most frequent parties:")
print(main['party'].value_counts().head(10))

# Missing values
null_party_count = main['party'].isna().sum()
print(f"\n❓ Missing 'party' values: {null_party_count}")

🔍 Total unique non-null parties: 48
📦 Top 10 most frequent parties:
party
VITOLSG       23426
GLENCORESG    21669
TRAFI         20376
SIETCO        12438
GUNVORSG      11652
TOTALSG       11223
MERCURIASG     7794
P66SG          7471
HL             7018
PETROCHINA     6404
Name: count, dtype: int64

❓ Missing 'party' values: 10411

In [ ]:
# Save the cleaned DataFrame
main.to_csv("heards_structured_cleaned_v10.csv", index=False)

# Download the file (Colab only)
from google.colab import files
files.download("heards_structured_cleaned_v10.csv")

In [ ]:
# Display 10 rows where 'party' is null
null_party_rows = main[main['party'].isnull()][['headline', 'price']].head(10)
display(null_party_rows)

,headline,price
154348,platts hsfo: physical offers finals on close (380 cst):,312.632611
154349,platts hsfo: platts hsfo: physical bids finals on close (380 cst):,303.076287
154350,platts hsfo: physical offers finals on close (180 cst):,309.246314
154351,platts bunker: 380 cst hsfo: delivered colombo: offer heard at $505/mt,287.948950
154352,platts hsfo: physical offers finals on close (380 cst):,312.632611
154353,platts hsfo: platts hsfo: physical bids finals on close (380 cst):,303.076287
154354,platts hsfo: physical offers finals on close (180 cst):,309.246314
154355,platts hsfo: physical offers finals on close (380 cst):,312.632611
154356,platts hsfo: platts hsfo: physical bids finals on close (380 cst):,303.076287
154357,platts hsfo: physical offers finals on close (180 cst):,309.246314

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving heards_structured_cleaned_10_Trades.csv to heards_structured_cleaned_10_Trades.csv

In [ ]:
import pandas as pd

# Load the uploaded CSV
main = pd.read_csv("heards_structured_cleaned_10_Trades.csv")

## 🧠  Party Classification Model

**Goal:**  
Train a machine learning model to predict the `party` column for rows where it is currently missing, based on the available features such as:

- `headline` (text)
- `price`, `price_basis`, `location`, etc. (structured features)

**Why this matters:**  
Around 10,000+ rows have missing `party` values. Many of these are repetitive benchmarks, but some may be classifiable based on pricing behavior and text patterns. By using a neural network, we aim to:

- Learn non-obvious patterns in text and pricing,
- Predict party labels for incomplete entries,
- Improve dataset completeness for downstream analysis.

We will:
1. Preprocess the dataset,
2. Tokenize and vectorize the `headline`,
3. Combine it with structured features,
4. Train a neural network to predict the party,
5. Apply the model to fill missing values where confidence is high.

In [ ]:
# Print % filled and total rows/columns
filled_percent = (main.notnull().mean() * 100).round(2)
print("📊 % of Filled Values per Column:\n")
print(filled_percent)

print("\n📄 Total Rows:", len(main))
print("📈 Total Columns:", len(main.columns))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             93.68
price            100.00
price_basis      100.00
location          89.78
volume_min        72.43
volume_max        72.43
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

📄 Total Rows: 164759
📈 Total Columns: 15

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# 1. Encode party labels (only non-null)
main_non_null = main[main['party'].notnull()].copy()
label_encoder = LabelEncoder()
main_non_null['party_encoded'] = label_encoder.fit_transform(main_non_null['party'])

# 2. Vectorize headline text with TF-IDF (limit features to 5000 for speed)
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
X_text = tfidf.fit_transform(main_non_null['headline'])

# 3. Prepare numeric features - price, price_basis (one-hot), volume_min/max, location (one-hot)
# One-hot encode categorical columns
price_basis_ohe = pd.get_dummies(main_non_null['price_basis'], prefix='price_basis')
location_ohe = pd.get_dummies(main_non_null['location'], prefix='loc')

# Combine numeric features
numeric_feats = main_non_null[['price', 'volume_min', 'volume_max']].fillna(0)
scaler = StandardScaler()
numeric_scaled = scaler.fit_transform(numeric_feats)

# Combine all features horizontally
from scipy.sparse import hstack
X = hstack([X_text, price_basis_ohe.values, location_ohe.values, numeric_scaled])

# Labels
y = main_non_null['party_encoded'].values

# 4. Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42, stratify=y)

print(f"Training samples: {X_train.shape[0]}, Testing samples: {X_test.shape[0]}")

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [ ]:
import numpy as np
from collections import Counter

# Count samples per class
class_counts = Counter(main_non_null['party_encoded'])
valid_classes = [cls for cls, count in class_counts.items() if count > 1]

# Filter dataset to only include valid classes
mask_valid = main_non_null['party_encoded'].isin(valid_classes)
main_filtered = main_non_null[mask_valid]

# Re-extract features and labels
y_filtered = main_filtered['party_encoded'].values
X_text_filtered = tfidf.transform(main_filtered['headline'])

price_basis_ohe_filtered = pd.get_dummies(main_filtered['price_basis'], prefix='price_basis')
location_ohe_filtered = pd.get_dummies(main_filtered['location'], prefix='loc')
numeric_feats_filtered = main_filtered[['price', 'volume_min', 'volume_max']].fillna(0)
numeric_scaled_filtered = scaler.transform(numeric_feats_filtered)

from scipy.sparse import hstack
X_filtered = hstack([X_text_filtered, price_basis_ohe_filtered.values, location_ohe_filtered.values, numeric_scaled_filtered])

# Train-test split with filtered data
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered, y_filtered, test_size=0.15, random_state=42, stratify=y_filtered)

print(f"Training samples: {X_train.shape[0]}, Testing samples: {X_test.shape[0]}")

Training samples: 131194, Testing samples: 23153

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

class PartyDataset(Dataset):
    def __init__(self, X_sparse, y):
        self.X = X_sparse
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        # Convert sparse row to dense tensor
        x = torch.tensor(self.X[idx].toarray(), dtype=torch.float32).squeeze(0)
        y = torch.tensor(self.y[idx], dtype=torch.long)
        return x, y

# Create datasets
train_dataset = PartyDataset(X_train, y_train)
test_dataset = PartyDataset(X_test, y_test)

# Create data loaders
batch_size = 256
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class PartyClassifier(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(PartyClassifier, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1024)
        self.dropout1 = nn.Dropout(0.3)
        self.fc2 = nn.Linear(1024, 512)
        self.dropout2 = nn.Dropout(0.3)
        self.fc3 = nn.Linear(512, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout1(x)
        x = F.relu(self.fc2(x))
        x = self.dropout2(x)
        x = self.fc3(x)
        return x

input_dim = X_train.shape[1]
num_classes = len(np.unique(y_train))

model = PartyClassifier(input_dim, num_classes).cuda()

In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

def train_epoch(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0
    for x_batch, y_batch in loader:
        x_batch, y_batch = x_batch.cuda(), y_batch.cuda()
        optimizer.zero_grad()
        outputs = model(x_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * x_batch.size(0)
    return total_loss / len(loader.dataset)

In [ ]:
def validate_epoch(model, loader, criterion):
    model.eval()
    total_loss = 0
    correct = 0
    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch, y_batch = x_batch.cuda(), y_batch.cuda()
            outputs = model(x_batch)
            loss = criterion(outputs, y_batch)
            total_loss += loss.item() * x_batch.size(0)
            preds = outputs.argmax(dim=1)
            correct += (preds == y_batch).sum().item()
    accuracy = correct / len(loader.dataset)
    return total_loss / len(loader.dataset), accuracy

In [ ]:
num_epochs = 5
best_val_acc = 0

for epoch in range(1, num_epochs + 1):
    train_loss = train_epoch(model, train_loader, optimizer, criterion)
    val_loss, val_acc = validate_epoch(model, test_loader, criterion)
    print(f"Epoch {epoch}: Train Loss={train_loss:.4f}, Val Loss={val_loss:.4f}, Val Acc={val_acc:.4f}")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_party_classifier.pth")
        print("Best model saved.")

Epoch 1: Train Loss=0.4525, Val Loss=0.0102, Val Acc=0.9986
Best model saved.
Epoch 2: Train Loss=0.0065, Val Loss=0.0045, Val Acc=0.9992
Best model saved.
Epoch 3: Train Loss=0.0034, Val Loss=0.0040, Val Acc=0.9993
Best model saved.
Epoch 4: Train Loss=0.0022, Val Loss=0.0046, Val Acc=0.9991
Epoch 5: Train Loss=0.0015, Val Loss=0.0042, Val Acc=0.9994
Best model saved.

In [ ]:
model.load_state_dict(torch.load("best_party_classifier.pth"))
model.eval()

PartyClassifier(
  (fc1): Linear(in_features=2890, out_features=1024, bias=True)
  (dropout1): Dropout(p=0.3, inplace=False)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (dropout2): Dropout(p=0.3, inplace=False)
  (fc3): Linear(in_features=512, out_features=47, bias=True)
)

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd

# Custom Dataset handling sparse matrix indexing properly
class NullPartyDataset(Dataset):
    def __init__(self, X):
        # Convert to CSR format for efficient row slicing
        self.X = X.tocsr()

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        x = torch.tensor(self.X[idx].toarray(), dtype=torch.float32).squeeze(0)
        return x

# Prepare data for null-party rows
null_party_df = main[main['party'].isnull()].copy()

# Vectorize headline text
X_text_null = tfidf.transform(null_party_df['headline'])

# One-hot encode price_basis and location, align columns with training data
price_basis_ohe_null = pd.get_dummies(null_party_df['price_basis'], prefix='price_basis')
location_ohe_null = pd.get_dummies(null_party_df['location'], prefix='loc')

# Add missing columns with zeros
for col in price_basis_ohe.columns:
    if col not in price_basis_ohe_null:
        price_basis_ohe_null[col] = 0
price_basis_ohe_null = price_basis_ohe_null[price_basis_ohe.columns]

for col in location_ohe.columns:
    if col not in location_ohe_null:
        location_ohe_null[col] = 0
location_ohe_null = location_ohe_null[location_ohe.columns]

# Scale numeric features
numeric_null = null_party_df[['price', 'volume_min', 'volume_max']].fillna(0)
numeric_null_scaled = scaler.transform(numeric_null)

from scipy.sparse import hstack
X_null = hstack([X_text_null, price_basis_ohe_null.values, location_ohe_null.values, numeric_null_scaled])

# Create Dataset and DataLoader
null_dataset = NullPartyDataset(X_null)
null_loader = DataLoader(null_dataset, batch_size=256, shuffle=False)

# Load best model and set to eval
model.load_state_dict(torch.load("best_party_classifier.pth"))
model.eval()

# Predict with confidence thresholding
predicted_parties = []
confidences = []

with torch.no_grad():
    for batch in null_loader:
        batch = batch.cuda()
        outputs = model(batch)
        probs = F.softmax(outputs, dim=1)
        conf, preds = torch.max(probs, dim=1)
        predicted_parties.extend(preds.cpu().numpy())
        confidences.extend(conf.cpu().numpy())

# Apply confidence threshold (e.g., 0.9)
threshold = 0.9
final_predictions = []
for conf, pred in zip(confidences, predicted_parties):
    if conf >= threshold:
        final_predictions.append(label_encoder.inverse_transform([pred])[0])
    else:
        final_predictions.append(None)

# Update main DataFrame
main.loc[null_party_df.index, 'party'] = final_predictions

In [ ]:
null_filled = main[main.index.isin(null_party_df.index)]

num_filled = null_filled['party'].notnull().sum()
num_remaining_null = null_filled['party'].isnull().sum()
total_null = len(null_filled)

print(f"Total previously null party rows: {total_null}")
print(f"Number of rows filled with confident predictions: {num_filled}")
print(f"Number of rows still null (low confidence): {num_remaining_null}")
print(f"Percentage filled: {num_filled / total_null * 100:.2f}%")

Total previously null party rows: 10411
Number of rows filled with confident predictions: 555
Number of rows still null (low confidence): 9856
Percentage filled: 5.33%

In [ ]:
# % filled per column
filled_percent = (main.notnull().mean() * 100).round(2)
print("📊 % of Filled Values per Column:\n")
print(filled_percent)

# Total number of rows
print("\n📄 Total Rows:", len(main))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party             94.02
price            100.00
price_basis      100.00
location          89.78
volume_min        72.43
volume_max        72.43
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

📄 Total Rows: 164759

In [ ]:
unique_parties = main['party'].dropna().unique()
print(f"Total unique non-null parties: {len(unique_parties)}")
print("Unique parties:\n", sorted(unique_parties))

Total unique non-null parties: 48
Unique parties:
 ['ALVARI', 'ARAMCOSG', 'ARAMCOTF', 'BBEN', 'BPSG', 'BRIGHTOILSG', 'CAOSG', 'CCMA', 'CHEVRONSG', 'CHIMB', 'COASTAL', 'ENEOSSG', 'ENOC', 'FREEPTSG', 'GLENCORESG', 'GPGLOBALSG', 'GULFSG', 'GUNVORSG', 'HL', 'IDEMITSU', 'ITGRES', 'KAIROS', 'LUKOIL', 'MACQUARIESG', 'MAERSKSG', 'MERCURIARESOURCES', 'MERCURIASG', 'MIPCO', 'NOVUMC', 'P66SG', 'PETCO', 'PETROCHINA', 'PTT', 'REPSOLSG', 'REXCOMM', 'RGES', 'SIETCO', 'SINOPECFO', 'SINOPECHKSG', 'SKEISG', 'SOCAR', 'TOTALSG', 'TRAFI', 'UNIPECSG', 'VITOLSG', 'WANXIANG', 'WELLBRED', 'ZENROCK']

In [ ]:
null_party_count = main['party'].isnull().sum()
print(f"Number of rows with null party: {null_party_count}")

Number of rows with null party: 9856

In [ ]:
null_party_count = main['party'].isnull().sum()
total_rows = len(main)
percent_null = (null_party_count / total_rows) * 100
print(f"Percentage of rows with null party: {percent_null:.2f}%")

Percentage of rows with null party: 5.98%

In [ ]:
import pandas as pd

null_party_headlines = main[main['party'].isnull()]['headline'].sample(50, random_state=42)
for i, headline in enumerate(null_party_headlines, 1):
    print(f"{i}. {headline}\n")

1. platts hsfo fob fuj: physical bids finals on close (380 cst):

2. platts hsfo: platts hsfo: physical bids finals on close (380 cst):

3. platts hsfo: platts hsfo: physical bids finals on close (380 cst):

4. platts hsfo: platts hsfo: physical bids finals on close (380 cst):

5. asia 487: platts hsfo: physical bids summary (380 cst)

6. platts hsfo: physical bids finals on close (380 cst):

7. platts hsfo: physical bids finals on close (180 cst):

8. asia 1396: platts hsfo fob fuj: physical bids finals on close (380 cst)

9. platts hsfo: physical offers finals on close (380 cst):

10. asia 1566: platts hsfo 380cst fob straits 15-30, trafi sells to hl mar 1, 2019-mar 5, 2019  100% mops 380 5 day $2.00  f

11. platts hsfo: physical offers finals on close (380 cst): take 2/2

12. asia 2102: platts hsfo 380cst fob straits 15-30, mercuriasg buys from glencoresg sep 8, 2017-sep 12, 2017  100% mops 380

13. platts hsfo: physical offers finals on close (180 cst):

14. asia 1393: platts hsfo: physical bids finals on close (180 cst)

15. platts hsfo: physical offers finals on close (180 cst):

16. platts hsfo: physical offers finals on close (380 cst):

17. asia 1476: platts hsfo: physical offers finals on close (180 cst)

18. platts hsfo: physical offers finals on close (380 cst):

19. asia 1474: platts hsfo 180cst fob straits 15-30, trafi sells to mercuriasg oct 9, 2018-oct 13, 2018  100% mops 180 flat

20. platts hsfo: physical offers finals on close (380 cst): part 3/4

21. platts hsfo: physical offers finals on close (180 cst):

22. asia 473: platts hsfo: physical offers summary (380 cst)

23. asia 1608: platts hsfo: physical bids finals on close (180 cst)

24. platts hsfo: physical bids finals on close (380 cst):

25. platts hsfo: physical bids finals on close (380 cst):

26. asia 1595: platts hsfo: physical offers finals on close (180 cst)

27. platts hsfo: platts hsfo: physical bids finals on close (380 cst):

28. asia 1258: platts hsfo fob fuj: physical bids finals on close (380 cst)

29. platts hsfo: physical offers finals on close (180 cst):

30. asia 1516: platts hsfo: physical bids finals on close (180 cst)

31. platts hsfo: physical bids finals on close (180 cst):

32. asia 1225: platts hsfo 380cst fob straits 15-30, mercuriasg buys from sietco jan 10, 2018-jan 14, 2018  100% mops 380 fl

33. asia 1724: platts hsfo: physical bids finals on close (180 cst)

34. platts emea bunkers: 3.5%s hsfo (380 cst) genoa heard at $441/mt ex-wharf

35. asia 474: platts hsfo: physical bids summary (180 cst)

36. platts hsfo: physical offers finals on close (380 cst):

37. asia 1555: platts hsfo fob fuj: physical bids finals on close (380 cst)

38. asia 1958: platts hsfo: physical offers finals on close (180 cst)

39. platts hsfo: platts hsfo: physical bids finals on close (380 cst):

40. platts hsfo: physical offers finals on close (380 cst):

41. asia 2072: platts hsfo: physical bids finals on close (380 cst)

42. platts hsfo: physical offers finals on close (380 cst):

43. asia 1805: platts hsfo fob fuj: physical offers finals on close (380 cst)

44. platts hsfo: physical offers finals on close (380 cst):

45. platts hsfo: physical bids finals on close (180 cst):

46. asia 1275: platts hsfo: physical offers finals on close (180 cst)

47. platts hsfo: physical bids finals on close (180 cst):

48. platts hsfo: physical offers finals on close (380 cst):

49. asia 1786: platts hsfo: physical offers finals on close (380 cst)

50. platts hsfo: physical bids finals on close (180 cst):

## Reason for Dropping Rows with Null `party`

In our dataset, approximately 6% of the rows have a missing `party` value. Upon inspection, these rows predominantly consist of:

- Generic benchmark or reference price reports (e.g., “physical bids finals on close”),
- Market summaries without explicit trade counterparties,
- Data entries lacking actionable party information.

Since our analysis and modeling focus on understanding trading behavior and party-specific patterns, including these ambiguous entries would introduce noise and reduce data quality.

**Therefore, to maintain dataset integrity and ensure meaningful downstream insights, we are dropping all rows where the `party` value is missing.**

This step improves:

- Accuracy of party-level analyses,
- Performance and reliability of machine learning models,
- Clarity in market interpretation.

This decision is consistent with best practices in commodity trade data preprocessing.

In [ ]:
main = main[main['party'].notnull()].reset_index(drop=True)

In [ ]:
# % of filled values per column
filled_percent = (main.notnull().mean() * 100).round(2)
print("📊 % of Filled Values per Column:\n")
print(filled_percent)

# Total number of rows
print("\n📄 Total Rows:", len(main))

📊 % of Filled Values per Column:

updatedDate      100.00
start_date       100.00
end_date         100.00
action_type      100.00
party            100.00
price            100.00
price_basis      100.00
location          95.49
volume_min        77.04
volume_max        77.04
headline         100.00
duration_days    100.00
start_month      100.00
end_month        100.00
price_raw        100.00
dtype: float64

📄 Total Rows: 154903

In [ ]:
main = main.drop(columns=['start_month', 'end_month', 'price_raw'])

In [ ]:
# Number and percentage of nulls in 'location'
num_null = main['location'].isnull().sum()
total_rows = len(main)
percent_null = (num_null / total_rows) * 100

print(f"Number of null 'location' rows: {num_null}")
print(f"Percentage of null 'location' rows: {percent_null:.2f}%")

# Unique non-null locations
unique_locations = main['location'].dropna().unique()
print(f"\nTotal unique non-null locations: {len(unique_locations)}")
print("Unique locations:")
print(sorted(unique_locations))

Number of null 'location' rows: 6981
Percentage of null 'location' rows: 4.51%

Total unique non-null locations: 3
Unique locations:
['Asia', 'Fujairah', 'Straits']

In [ ]:
null_location_headlines = main[main['location'].isnull()]['headline'].sample(5, random_state=42)
for i, headline in enumerate(null_location_headlines, 1):
    print(f"{i}. {headline}\n")

1. Platts HSFO 380cst FOB ID 15-30, VITOLSG lowers offer Nov 3-Nov 7 100% MOPS 380 Flat Price $347.00  for 20-20 "KARIMUN,

2. Platts HSFO 180cst FSU 15-30, P66SG lowers offer Mar 6-Mar 10 100% MOPS 180 Flat Price $395.00  for 20-20 "EM Splendour

3. Platts HSFO 380cst FSU 15-30, P66SG <P>  offers Oct 14-Oct 18 100% MOPS 380 5 Day $2.00  for 20-20 "EM Splendour & BP 20

4. Platts HSFO 180cst FSU 15-30, P66SG offers Mar 4-Mar 8 100% MOPS 180 Flat Price $427.00  for 20-20 "FSU EM Splendsour /

5. Platts HSFO 380cst FSU 15-30, TRAFI lowers offer May 19-May 23 100% MOPS 380 Half Mnth H2 May $3.00  for 20-20 "FSU SA O

In [ ]:
known_location_rows = main[main['location'].notnull()][['headline', 'location']].sample(5, random_state=42)
for i, row in enumerate(known_location_rows.itertuples(), 1):
    print(f"{i}. Location: {row.location}\n   Headline: {row.headline}\n")

1. Location: Straits
   Headline: Platts HSFO 180cst FOB Straits 15-30, GUNVORSG raises bid Aug 1-Aug 5 100% MOPS 180 5 Day $-7.00  for 40-40 OCO  8:14:09

2. Location: Straits
   Headline: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Jul 21-Jul 25 100% MOPS 380 Flat Price $232.00  for 20-20

3. Location: Asia
   Headline: Asia 243: Platts HSFO 380cst FOB Straits 15-30, TRAFI bids Sep 24-Sep 28 100% MOPS 380 5 Day $1.00  for 20-20 7:58:58.83

4. Location: Asia
   Headline: Asia 978: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Oct 8-Oct 12 100% MOPS 380 BalMnth Bal Month $19

5. Location: Asia
   Headline: Asia 308: Platts HSFO 380cst FOB Straits 15-30, VITOLSG lowers offer Jan 20-Jan 24 100% MOPS 380 5 Day $9.00  for 20-20

In [ ]:
# Save the DataFrame
main.to_csv("heards_structured_cleaned_v11.csv", index=False)

# Download in Colab
from google.colab import files
files.download("heards_structured_cleaned_v11.csv")

In [ ]:
import pandas as pd

random_headlines = main['headline'].sample(50, random_state=42)
for i, headline in enumerate(random_headlines, 1):
    print(f"{i}. {headline}\n")

1. Asia 527: Platts HSFO 380cst FOB Straits 15-30, PTT raises bid Oct 29-Nov 2 100% MOPS 380 Flat Price $290.00  for 20-20

2. Asia 776: Platts HSFO 380cst FOB Straits 15-30, GUNVORSG raises bid Oct 2-Oct 6 100% MOPS 380 5 Day $33.00  for 40-40 OC

3. Asia 228: Platts HSFO 380cst FOB Straits 15-30, HL bids Nov 17-Nov 21 100% MOPS 380 Full Mnth Nov $0.00  for 20-20 "INCO

4. Asia 1554: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Feb 4-Feb 8 100% MOPS 380 5 Day $1.00  for 20-2

5. Asia 235: Platts HSFO 180cst FOB Straits 15-30, TRAFI bids Dec 12-Dec 16 100% MOPS 180 5 Day $4.00  for 20-20 "inco" 7:5

6. Asia 865: Platts HSFO 380cst FOB Straits 15-30, GUNVORSG raises bid Jul 17-Jul 21 100% MOPS 380 5 Day $4.00  for 40-40 "

7. Platts HSFO 380cst FOB Straits 15-30, TOTALSG lowers offer Jul 31-Aug 4 100% MOPS 380 BalMnth Bal Month $2.00  for 20-20

8. Asia 313: Platts HSFO 380cst FOB Straits 15-30, SIETCO bids Sep 11-Sep 15 100% MOPS 380 5 Day $2.00  for 20-20 OCO  7:56

9. Asia 1412: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG raises bid May 25-May 29 100% MOPS 380 Flat Price $424.50  f

10. Asia 890: Platts HSFO 180cst FOB Straits 15-30, GUNVORSG raises bid Jan 4-Jan 8 100% MOPS 180 5 Day $-1.00  for 20-20 "i

11. Platts HSFO 380cst FOB Straits 15-30, GLENCORESG withdraws offer Aug 11-Aug 15 100% MOPS 380 5 Day $1.00  for 20-20 OCO

12. Platts HSFO 380cst FOB Straits 15-30, GUNVORSG lowers offer Jun 22-Jun 26 100% MOPS 380 5 Day $5.00  for 20-20 "INCO" OC

13. Asia 1700: Platts HSFO 380cst FOB Straits 15-30, TRAFI bids on Dec 27-Dec 31 100% MOPS 380 5 Day $7.00  for 20-20 "incot

14. Asia 534: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Mar 20-Mar 24 100% MOPS 380 Flat Price $432.00

15. Platts HSFO 380cst FOB Straits 15-30, PTT raises bid Sep 8-Sep 12 100% MOPS 380 5 Day $2.00  for 40-40 "INCO" OCO  8:15:

16. Platts HSFO 380cst FOB Straits 15-30, GLENCORESG offers Jun 11-Jun 15 100% MOPS 380 5 Day $5.00  for 20-20 OCO  7:57:25.

17. Platts HSFO 180cst FOB Straits 15-30, VITOLSG raises bid Mar 6-Mar 10 100% MOPS 180 5 Day $5.00  for 20-20 "INCO" 8:16:0

18. Asia 131: Platts HSFO 180cst FOB Straits 15-30, VITOLSG bids Sep 25-Sep 29 100% MOPS 180 5 Day $1.00  for 20-20 "inco" O

19. Platts HSFO 380cst FOB Straits 15-30, SIETCO lowers offer May 25-May 29 100% MOPS 380 5 Day $1.00  for 20-20 "Shell GTC"

20. Asia 1100: Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Oct 9-Oct 13 100% MOPS 380 5 Day $33.00  for 20-20 "in

21. Asia 215: Platts HSFO 180cst FOB Straits 15-30, GUNVORSG offers Mar 24-Mar 28 100% MOPS 380 Full Mnth Mar $10.00  for 20

22. Asia 1203: Platts HSFO 180cst FOB Straits 15-30, VITOLSG raises bid Jul 17-Jul 21 100% MOPS 180 5 Day $3.00  for 27-27 "

23. Asia 522: Platts HSFO 180cst FOB Straits 15-30, VITOLSG raises bid Jan 13-Jan 17 100% MOPS 180 5 Day $-3.00  for 20-20 "

24. Asia 874: Platts HSFO 380cst FOB Straits 15-30, GUNVORSG lowers offer Mar 17-Mar 21 100% MOPS 380 Full Mnth Mar $1.00  f

25. Asia 338: Platts HSFO 380cst FOB Straits 15-30, VITOLSG raises bid Jun 11-Jun 15 100% MOPS 380 Full Mnth Jun $-1.00  for

26. Asia 1498: Platts HSFO 380cst FOB Straits 15-30, HL raises bid Sep 22-Sep 26 100% MOPS 380 BalMnth Bal Month $0.50  for

27. Asia 1645: Platts HSFO 380cst FOB Straits 15-30, SIETCO lowers offer Oct 31-Nov 4 100% MOPS 380 BalMnth Bal Month $9.00

28. Platts HSFO 180cst FOB Straits 15-30, GUNVORSG offers Jan 12-Jan 16 100% MOPS 180 Full Mnth Jan $5.00  for 20-20 "INCO "

29. Asia 443: Platts HSFO 380cst FOB Straits 15-30, COASTAL amends bid Aug 16-Aug 20 100% MOPS 380 Flat Price $290.00  for 2

30. Platts HSFO 180cst FOB Straits 15-30, VITOLSG raises bid Mar 22-Mar 26 100% MOPS 180 5 Day $3.00  for 20-20 "inco" 8:13:

31. Asia 1087: Platts HSFO 380cst FOB Straits 15-30, SINOPECHKSG  raises bid Sep 26-Sep 30 100% MOPS 380 Full Mnth Oct $46.0

32. Asia 1507: Platts HSFO 380cst FOB Straits 15-30, VITOLSG withdraws offer Oct 15-Oct 19 100% MOPS 380 5 Day $5.00  for 20

33. Platts HSFO 180cst FOB Straits 15-30, PETROCHINA lowers offer Aug 31-Sep 4 100% MOPS 380 BalMnth Bal Month $13.75  for 2

34. Platts HSFO 180cst FOB Straits 15-30, MERCURIARESOURCES lowers offer Apr 23-Apr 27 100% MOPS 180 5 Day $3.00  for 20-20

35. Asia 861: Platts HSFO 180cst FSU 15-30, TRAFI lowers offer Dec 24-Dec 28 100% MOPS 180 5 Day $0.00  for 20-20 "jubilee s

36. Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Oct 8-Oct 12 100% MOPS 380 5 Day $1.00  for 20-20 "inco" OCO  8:2

37. Platts HSFO 380cst FOB Straits 15-30, PETROCHINA bids Nov 14-Nov 18 100% MOPS 380 5 Day $1.00  for 30-30 "inco" OCO  7:5

38. Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Aug 14-Aug 18 100% MOPS 380 Flat Price $258.00  for 20-20

39. Platts HSFO 380cst FSU 15-30, TRAFI lowers offer May 29-Jun 2 100% MOPS 380 5 Day $2.00  for 20-20 "FSU SA OCEANIA" OCO

40. Platts HSFO 180cst FOB Straits 15-30, TOTALSG lowers offer Apr 14-Apr 18 100% MOPS 180 5 Day $4.00  for 20-20 "Total GTC

41. Asia 610: Platts HSFO 380cst FOB Straits 15-30, VITOLSG raises bid Jul 12-Jul 16 100% MOPS 380 5 Day $1.00  for 20-20 "i

42. Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Aug 22-Aug 26 100% MOPS 380 5 Day $16.00  for 20-20 OCO  8:03:48.

43. Asia 432: Platts HSFO 380cst FOB Straits 15-30, HL lowers offer Apr 8-Apr 12 100% MOPS 380 Flat Price $364.00  for 20-20

44. Asia 1184: Platts HSFO 380cst FOB Straits 15-30, VITOLSG lowers offer Feb 17-Feb 21 100% MOPS 380 Full Mnth Feb $1.00  f

45. Asia 596: Platts HSFO 380cst FOB Straits 15-30, GLENCORESG lowers offer Sep 15-Sep 19 100% MOPS 380 Full Mnth Sep $24.00

46. Asia 260: Platts HSFO 180cst FOB Straits 15-30, VITOLSG bids Jul 23-Jul 27 100% MOPS 180 5 Day $1.00  for 20-20 "INCO" O

47. Asia 910: Platts HSFO 380cst FOB Straits 15-30, ENOC raises bid Jul 14-Jul 18 100% MOPS 380 5 Day $2.00  for 20-20 "Inco

48. Platts HSFO 380cst FOB Straits 15-30, VITOLSG bids Aug 24-Aug 28 100% MOPS 380 5 Day $15.00  for 20-20 "INCO" OCO  7:58:

49. Platts HSFO 380cst FOB Straits 15-30, TRAFI raises bid Mar 30-Apr 3 100% MOPS 380 5 Day $-4.50  for 40-40 OCO  8:20:52.1

50. Asia 793: Platts HSFO 180cst FOB Straits 15-30, GUNVORSG raises bid Jun 17-Jun 21 100% MOPS 180 5 Day $1.50  for 20-20 O